name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config user.email '${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com'
          git config user.name '${GITHUB_ACTOR}'
      - name: Add permissions
        run: |
          chmod +x ./tests/update_tags_tests.sh
          chmod +x ./update_tags.sh
      - name: Run tests
        run: ./tests/update_tags_tests.sh
        shell: bash
